services:
  - name: whoogle-search
    type: web
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: ./run
    region: oregon
    repo: https://github.com/benbusby/whoogle-search
    branch: main
    healthCheckPath: /
    envVars:
      - key: WHOOGLE_CONFIG_PATH
        value: /app/config.yaml
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 60  # Added this field
    disk:
      name: whoogle-data
      mountPath: /app/data
      sizeGB: 5
